version: '1.0'

services:
  cups:
    container_name: cups
    image: janmorano/docker-cups-airprint
    #build: .
    restart: always
    network_mode: "_maclan.network"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
    volumes:
      - "./services:/services"
      - "./config:/config"
